### PR TITLE
Allow skipping of Welcome on programattic activation

### PR DESCRIPTION
**Pull request by tylercollier**
For #347

There, I had suggested putting a value in the database. It seems better to use a constant.

I named it prefixed with `STRONG_TESTIMONIALS`, as opposed to `WPMTST`, thinking that `WPMTST` is perhaps meant for internal use and I shouldn't hijack it. But by all means, feel free to change it.

### CODE REVIEW

**Comment by cristianraiber** [comment]
I guess we could add an if(class_exists()) on WPMST_WELCOME(), this way, you could define your own class (like you did in the issue you've opened) and overwrite our own. Wouldn't this make more sense that using a constant? Just thinking out loud here.

**Comment by tylercollier** [comment]
Oh, you mean like this?

```php
if (class_exists('Strong_Testimonials_Welcome')) {
	new Strong_Testimonials_Welcome();
	do_action( 'wpmtst_after_update_setup', $first_install );	
}
```

Yup, that looks good. I'll update the PR.

**Comment by tylercollier** [comment]
The PR is very simple. I didn't bother to comment it, but you might want to as the scenario might be tough to remember.

```
// If the plugin is being activated via activate_plugin(), and is_admin() is false, perhaps because the code is run in a register_rest_route callback, then `Strong_Testimonials_Welcome` won't have been `require_once`d in `Strong_Testimonials->includes()`.
if (class_exists('Strong_Testimonials_Welcome')) {
...
``

**Comment by tylercollier** [comment]
Perhaps another way, without an awkward comment like that, would be:

```php
if ( is_admin() || ( defined( 'WP_CLI' ) && WP_CLI ) ) {
	new Strong_Testimonials_Welcome();
	do_action( 'wpmtst_after_update_setup', $first_install );
}
```

Ideally you could DRY up that `if ( is_admin() || ( defined( 'WP_CLI' ) && WP_CLI ) ) {` because it's used there as well as in `Strong_Testimonials->includes()`.

**Comment by tylercollier** [comment]
Can you explain why this was closed? I don't see the functionality in 3.1.0.

**Comment by razvanaldea89** [comment]
Wasn't closed, the branch was deleted by mistake and the PR self closed.

**Pull request merged**
